### PR TITLE
upgrade to latest fp-ts

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

**Comment by gcanti** [comment]
@sledorze real world usage of `NonEmptyArray2v` :)

**Comment by sledorze** [comment]
@gcanti oh that's beautiful :) eager to use it!!

**Comment by sledorze** [comment]
@gcanti for what it's worth, I ve switch our whole code base to it.
No problem.
It simplifies a lot.

**Comment by gcanti** [comment]
@sledorze Nice! Thanks for the feedback

**Pull request merged**
